### ISSUE TITLE
search bar not responsive when copy all button is clicked

### ISSUE THREAD

**Issue by DrakonDarquesse** [GervinFung/gitignored#61]
## How to reproduce
1. select one or more templates
2. click the blue button beside the searchbar named `Copy All`

## Expected behaviour
1. the spacing between the button and its surrounding elements will not change, but instead the size of the elements should be responsive

## Current behaviour
1. the increase in length of the `copy all` button uses up spacing of between the button and the searchbar

![image](https://github.com/GervinFung/gitignored/assets/44579558/51e7482c-efb7-486a-8685-e5a28e09d958)

**Comment by GervinFung** [comment]
@DrakonDarquesse issue resolved with feedback done through popup
